spring:
  application:
    name: 'SpringHttpClientTest'

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/advertisement
    username: user1
    password: password

  jpa:
    database: postgresql
